coverage:
  round: down
  precision: 5
  status:
    project:
      default:
        target: 85%
        threshold: 0%
        flags:
          - "unit"
        paths:
          - "/"
    patch:
      default:
          target:  85%
          threshold: 0%
          flags:
            - "unit"
          paths:
            - "/"
