coverage:
  status:
    project:
        default:
        # basic
        target: 84%
        threshold: 0%
        base: auto 
        flags: 
          - unit
    patch:
      default:
        # basic
        target:  84%
        threshold: 0%
        base: auto 
        # advanced
        branches: 
          - master
        if_ci_failed: error #success, error
        only_pulls: false
        flags: 
          - "unit"
