coverage:
  status:
    project:
      default:
        # basic
        target: 84%
        threshold: 0%
        base: auto 
        flags: 
          - unit
    patch: 
        default:
        # basic
        target: 84%
        threshold: 0%
        base: auto 
        flags: 
          - unit
