coverage:
  status:
    project:
      default:
        target: 84%
        threshold: 0%
        flags:
          - "project-unit"
        paths:
          - "./"
    patch:
      default:
          target:  84%
          threshold: 0%
          flags:
            - "patch-unit"
          paths:
            - "./"
